# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    i686-linux = "1602bpl1nf9bjlbvj2qwlwmjfxi2cwxask16h4r6p5sx2gdldibc";
    x86_64-linux = "18ncr3zrq85xf71qji2lpcnzjrclmw5l3749l2nnqbdbg8rc4mdq";
    aarch64-linux = "1kjnh0qll4pnfj9n13vw2ycwg0klhb9sz5pkvwca7f5ax3vvygvf";
    x86_64-darwin = "126q9hkpm2jk2a9gdpnciwyivdc05fnqahyf6lwx7nz55a6wb2bl";
    aarch64-darwin = "12321n854ywbg1nvma0iacphlr264wcxpc04bp02sl6w95nx0dnk";
  };

  urlMap = {
    i686-linux = "https://download.runway.horse/runway/1.30.1/runway_Linux_i386.tar.gz";
    x86_64-linux = "https://download.runway.horse/runway/1.30.1/runway_Linux_x86_64.tar.gz";
    aarch64-linux = "https://download.runway.horse/runway/1.30.1/runway_Linux_arm64.tar.gz";
    x86_64-darwin = "https://download.runway.horse/runway/1.30.1/runway_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://download.runway.horse/runway/1.30.1/runway_Darwin_arm64.tar.gz";
  };
  sourceRootMap = {
    i686-linux = "runway_Linux_i386";
    x86_64-linux = "runway_Linux_x86_64";
    aarch64-linux = "runway_Linux_arm64";
    x86_64-darwin = "runway_Darwin_x86_64";
    aarch64-darwin = "runway_Darwin_arm64";
  };
in
stdenvNoCC.mkDerivation {
  pname = "runway";
  version = "1.30.1";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = sourceRootMap.${system};

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./runway $out/bin/runway
  '';

  system = system;

  meta = {
    description = "The runway CLI.";
    homepage = "https://runway.planetary-quantum.com/";
    license = lib.licenses.unfree;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
