# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    i686-linux = "0gq08cdyc1cl589viiyxpsw7zrhrlv0n0m6ic2vd3xzrlwl23cdl";
    x86_64-linux = "1b249b0fhpc5knqnr16621hpjn5a9a4r2iqgkckmakrg69rixgkd";
    aarch64-linux = "1ikfajxwap1xzwndncv13kn01fcygsccx0m49b67vfvxckcn8kll";
    x86_64-darwin = "1gl91rljqj4fify51m9zz05d7n0x1s7pmvayk7razv1yvc366cm0";
    aarch64-darwin = "07fi6s7zk5g5mrl3zsbnfrg60w4bjci2aj6glywv06nqabdzrkdd";
  };

  urlMap = {
    i686-linux = "https://download.runway.horse/runway/1.5.3/runway_Linux_i386.tar.gz";
    x86_64-linux = "https://download.runway.horse/runway/1.5.3/runway_Linux_x86_64.tar.gz";
    aarch64-linux = "https://download.runway.horse/runway/1.5.3/runway_Linux_arm64.tar.gz";
    x86_64-darwin = "https://download.runway.horse/runway/1.5.3/runway_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://download.runway.horse/runway/1.5.3/runway_Darwin_arm64.tar.gz";
  };
  sourceRootMap = {
    i686-linux = "runway_Linux_i386";
    x86_64-linux = "runway_Linux_x86_64";
    aarch64-linux = "runway_Linux_arm64";
    x86_64-darwin = "runway_Darwin_x86_64";
    aarch64-darwin = "runway_Darwin_arm64";
  };
in
stdenvNoCC.mkDerivation {
  pname = "runway";
  version = "1.5.3";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = sourceRootMap.${system};

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./runway $out/bin/runway
  '';

  system = system;

  meta = {
    description = "The runway CLI.";
    homepage = "https://runway.planetary-quantum.com/";
    license = lib.licenses.unfree;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
