# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    i686-linux = "143625bz844jnvnicjp8mai4sh7n671iv3bgwf5kkfdsyjyyrfv3";
    x86_64-linux = "0nwfcabx6x8k9b07xp5dx0nxixm30ayaq8nxj5y9wmzifbpcbyyg";
    aarch64-linux = "10zccdidbfh4rmm96s53r9053f9x4dmgp45hxjhnxqz1k2q0kv0b";
    x86_64-darwin = "0l0pprrilgm4rlsp2j8jp80p6wgwz0n1hp93hj66kr7zwhh679lf";
    aarch64-darwin = "1d4ll5zwkbag9f92r86i16q760mg0770v836ismplb01hmx7n87z";
  };

  urlMap = {
    i686-linux = "https://download.runway.horse/runway/1.15.0/runway_Linux_i386.tar.gz";
    x86_64-linux = "https://download.runway.horse/runway/1.15.0/runway_Linux_x86_64.tar.gz";
    aarch64-linux = "https://download.runway.horse/runway/1.15.0/runway_Linux_arm64.tar.gz";
    x86_64-darwin = "https://download.runway.horse/runway/1.15.0/runway_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://download.runway.horse/runway/1.15.0/runway_Darwin_arm64.tar.gz";
  };
  sourceRootMap = {
    i686-linux = "runway_Linux_i386";
    x86_64-linux = "runway_Linux_x86_64";
    aarch64-linux = "runway_Linux_arm64";
    x86_64-darwin = "runway_Darwin_x86_64";
    aarch64-darwin = "runway_Darwin_arm64";
  };
in
stdenvNoCC.mkDerivation {
  pname = "runway";
  version = "1.15.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = sourceRootMap.${system};

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./runway $out/bin/runway
  '';

  system = system;

  meta = {
    description = "The runway CLI.";
    homepage = "https://runway.planetary-quantum.com/";
    license = lib.licenses.unfree;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
